const DISCORD='https://discord.gg/3hTnm3Pgy2';
const SOCIAL_LINKS={instagram:'https://www.instagram.com/awakencult/',x:'https://x.com/awakencult',youtube:'https://www.youtube.com/@awakencult'};
const apps=[
 {id:'readme',label:'README.txt',icon:'R',cls:'ico-readme',type:'readme'},
 {id:'social',label:'CULTFEED',icon:'CF',cls:'ico-social',type:'social'},
 {id:'music',label:'MUSIC.EXE',icon:'M',cls:'ico-music',type:'music'},
 {id:'collection',label:'COLLECTION.EXE',icon:'C',cls:'ico-collection',type:'collection'},
 {id:'discord',label:'DISCORD.LNK',icon:'D',cls:'ico-discord',type:'discord'},
 {id:'archive',label:'ARCHIVE',icon:'A',cls:'ico-archive',type:'archive'},
 {id:'aim',label:'AIM_CHAT',icon:'AIM',cls:'ico-aim',type:'aim'},
 {id:'memory',label:'MEMORY_CARD',icon:'PS2',cls:'ico-memory',type:'memory'},
 {id:'tv',label:'CHANNEL_TV',icon:'TV',cls:'ico-tv',type:'tv'},
 {id:'downloads',label:'DOWNLOADS',icon:'DL',cls:'ico-downloads',type:'downloads'},
 {id:'trash',label:'TRASH',icon:'X',cls:'ico-trash',type:'trash'}
];
const socialPosts=[
 {src:'Instagram relay',date:'RECOVERED POST',text:'Noise Collection & Magazine Out Now. All Seeing Hoodie. Restock of older collections also available. Enjoy ☻',tag:'@awakencult'},
 {src:'X relay',date:'2021 cache',text:'NEW SWAG WHO DIS? — Single by AWAKEN CULT, Josh Otis & PARI$. Listen now on your favorite streaming service.',tag:'release.link'},
 {src:'YouTube relay',date:'old upload cache',text:'SUNNY - Josh Otis visualizer / PLANETPRADA - PARI$ / AWAKE audio fragments indexed.',tag:'video archive'}
];
const bootMessages=['AWAKEN NETWORK BIOS v06.26','CPU: CULT CORE / 256MB MEMORY','detecting old hard drive... OK','mounting XP fragments... OK','checking AIM buddies... 5 online','reading PS2 memory card... corrupted save found','tuning channel 04... static','loading social relay @awakencult... fallback cache online','press ENTER to boot'];
const popupData=[
 {t:'AWAKEN NETWORK SECURITY',b:'Your signal is exposed. Scan archive now?',kind:'virus',cta:'SCAN'},
 {t:'2 EASY PMTS OF $20.15',b:'GET GIFTS IRL // AWAKEN DELIVERY CACHE',kind:'gif',cta:'CLAIM'},
 {t:'COLLECTION DETECTED',b:'4 garments found. Preview thumbnails corrupted.',kind:'ad',cta:'OPEN'},
 {t:'CALL MY LAWYER',b:'MARKET Studios Creative Dept. wants this window closed.',kind:'blue',cta:'IGNORE'},
 {t:'AIM SYSTEM MSG',b:'A newer version of AWAKEN CHAT is available. Continue using this one?',kind:'ad',cta:'CONTINUE'},
 {t:'FREE WALLPAPER PACK',b:'Download boot screen, icon sheet, signal poster.',kind:'gif',cta:'DOWNLOAD'}
];
let z=20,logoClicks=0,sound=true,bootDone=false,konami=[],openWindows=new Map();
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
window.addEventListener('DOMContentLoaded',init);
function init(){makeBeep();$('#bootButton').addEventListener('click',finishBoot);$('#boot').addEventListener('click',e=>{if(e.target.id!=='bootButton')finishBoot()});document.addEventListener('keydown',globalKeys);runBoot();}
function runBoot(){let i=0;const pre=$('#bootLines'),bar=$('#bootProgress');function next(){pre.textContent+=bootMessages[i]+'\n';bar.style.width=((i+1)/bootMessages.length*100)+'%';i++; if(i<bootMessages.length)setTimeout(next,230+Math.random()*180);else bootDone=true;}next();}
function finishBoot(){if(!bootDone){bootDone=true}$('#boot').classList.add('hidden');$('#app').classList.remove('hidden');renderDesktop();tickClock();setInterval(tickClock,1000);setTimeout(()=>openApp('readme'),450);setTimeout(()=>openApp('social'),900);setTimeout(()=>spawnAd(),1600);setInterval(()=>Math.random()<.38&&spawnAd(),8500);toast('AWAKEN NETWORK ONLINE');}
function renderDesktop(){const icons=$('#icons');icons.innerHTML='';apps.forEach(a=>{const b=document.createElement('button');b.className='desk-icon';b.dataset.open=a.id;b.innerHTML=`<span class="icon-img ${a.cls}">${a.icon}</span><span class="icon-label">${a.label}</span>`;icons.appendChild(b)});document.addEventListener('click',e=>{const open=e.target.closest('[data-open]');if(open){openApp(open.dataset.open);playBeep()} });$('#startBtn').onclick=()=>$('#startMenu').classList.toggle('hidden');$('#muteBtn').onclick=()=>{sound=!sound;$('#muteBtn').textContent=sound?'SND ON':'SND OFF';toast(sound?'sound enabled':'sound muted')};$('#panicBtn').onclick=()=>{spawnAd('AWAKEN NETWORK SECURITY');spawnAd('SYSTEM WARNING');toast('scan started')};$('#shutdownBtn').onclick=()=>{toast('shutdown cancelled. system wants to stay awake.');$('#startMenu').classList.add('hidden')};$('.boot-logo')?.addEventListener('click',()=>{});$('.start-chip').addEventListener('dblclick',()=>spawnAd('SECRET START MENU'));$('.hero-terminal').addEventListener('click',()=>{logoClicks++; if(logoClicks===5){toast('UNKNOWN_USER unlocked');openApp('aim','unknown_user')}})}
function tickClock(){const d=new Date();$('#clock').textContent=d.toLocaleTimeString([], {hour:'2-digit', minute:'2-digit'});$('#signalText').textContent='SIGNAL: '+(58+Math.floor(Math.random()*23))+'%'}
function globalKeys(e){if($('#boot')&&!$('#boot').classList.contains('hidden')&&(e.key==='Enter'))finishBoot();konami.push(e.key.toLowerCase());konami=konami.slice(-10);if(konami.join(',')==='arrowup,arrowup,arrowdown,arrowdown,arrowleft,arrowright,arrowleft,arrowright,b,a'){toast('secret transmission unlocked');openApp('archive','secret');document.body.classList.add('glitch');setTimeout(()=>document.body.classList.remove('glitch'),900)} if(e.key.toLowerCase()==='x')window._xTyped=(window._xTyped||'')+'x'; const typed=(window._typed=(window._typed||'')+e.key.toLowerCase()).slice(-8); if(typed.includes('xp')){openApp('memory');window._typed='';}}
function openApp(id,param){const app=apps.find(a=>a.id===id);if(!app)return;$('#startMenu').classList.add('hidden');if(openWindows.has(id)){const win=openWindows.get(id);win.style.zIndex=++z;win.classList.add('active');return}const win=document.createElement('section');win.className='window active';win.dataset.id=id;win.style.zIndex=++z;let pos=randomPos();win.style.left=pos.x+'px';win.style.top=pos.y+'px';win.innerHTML=`<header class="titlebar"><span>${app.label}</span><span class="controls"><button data-min="${id}">_</button><button data-close="${id}">×</button></span></header><div class="window-body">${renderBody(app,param)}</div>`;$('#windows').appendChild(win);openWindows.set(id,win);makeDrag(win);updateTasks();wireWindow(win,id);}
function randomPos(){const w=window.innerWidth;return {x:Math.max(8,Math.min(130,Math.floor(Math.random()*160))),y:Math.max(8,Math.min(120,Math.floor(Math.random()*130)))} }
function renderBody(app,param){switch(app.type){
 case 'readme': return `<div class="notepad">AWAKEN NETWORK README\n\nThis is not a store yet. It is the machine before the drop.\n\nOpen files. Trigger ads. Break windows. Follow the social relay.\n\nTips:\n- type XP anywhere\n- use ↑ ↑ ↓ ↓ ← → ← → B A\n- click the terminal 5 times\n- some ads unlock real windows\n\nNEXT PATCH:\nmusic snippets / collection thumbnails / roles / archive uploads</div>`;
 case 'discord': return `<div class="dialog"><h2>SERVER FOUND</h2><p>AWAKEN CULT COMMUNITY<br>connection available. enter room?</p><p><a class="red-button" target="_blank" href="${DISCORD}">ENTER ROOM</a> <button class="xp-button" data-action="spawn">NOT NOW</button></p><small>Invite: ${DISCORD}</small></div>`;
 case 'music': return `<div class="winamp"><div class="winamp-top">AWAKEN WINAMP 2.06<br>NOW PLAYING: UNKNOWN SIGNAL<br>source: AWAKEN CULT // quality: damaged</div><div class="eq">${'<i></i>'.repeat(18)}</div><div class="playlist"><div class="track"><span>1. UNKNOWN SIGNAL</span><span>00:17</span></div><div class="track"><span>2. XPV2 FRAGMENT</span><span>00:09</span></div><div class="track locked"><span>3. REDACTED</span><span>--:--</span></div><div class="track locked"><span>4. CENTRAL AFRICAN TIME DEMO</span><span>locked</span></div></div><div class="music-controls"><button class="xp-button" data-action="play">PLAY TONE</button><button class="xp-button" data-action="glitch">VISUALIZE</button></div></div>`;
 case 'collection': return `<h3>COLLECTION PACKAGE</h3><pre>PACKAGE STATUS: INCOMPLETE\ngarments detected: 04\npublic preview: disabled\ninstall date: unknown</pre><div class="inventory-grid">${[1,2,3,4].map(i=>`<div class="garment"><b>GARMENT_0${i}.pkg</b><small>metadata damaged</small></div>`).join('')}</div><p><button class="xp-button" data-action="ad">RUN INSTALLER</button></p>`;
 case 'archive': return `<div class="browserbar"><button>Back</button><input value="C:\\AWAKEN\\ARCHIVE${param==='secret'?'\\SECRET':''}" readonly></div><pre>Recovered files may be incomplete. Some folders require a stronger signal.</pre><div class="file-list">${['XP','XPV2','HATED','STATE_OF_MIND','CENTRAL_AFRICAN_TIME','NOISE_COLLECTION','VISUALS','FINAL_FINAL.psd','CORRUPTED_SAVE','transmission.wav'].map((n,i)=>`<div class="file-row"><span>${i>6?'?':'▣'}</span><span>${n}</span><span>${i>7?'2kb':'locked'}</span><span>200${i%8+1}-??-??</span></div>`).join('')}</div>`;
 case 'social': return `<div class="social-shell"><div class="social-header"><span>CULTFEED / social relay</span><span>@awakencult</span></div><div class="profile"><div class="profile-eye">◉</div><div><b>AWAKEN CULT</b><br><small>art / fashion / music / signal</small><p><a class="xp-button" target="_blank" href="${SOCIAL_LINKS.instagram}">Instagram</a> <a class="xp-button" target="_blank" href="${SOCIAL_LINKS.x}">X</a> <a class="xp-button" target="_blank" href="${SOCIAL_LINKS.youtube}">YouTube</a></p></div></div>${socialPosts.map(p=>`<article class="feed-card"><header><b>${p.src}</b><small>${p.date}</small></header><div class="feed-media"></div><p>${p.text}</p><p><small>${p.tag}</small></p></article>`).join('')}</div>`;
 case 'aim': return renderAim(param);
 case 'memory': return `<div class="memory-screen"><div class="memory-head"><span>Memory Card (PS2) / 1</span><span>AWAKEN</span></div><div class="saves">${['XP','XPV2','HATED','STATE','C.A.T','COLL_26','VISUALS','???'].map(s=>`<button class="save"><span class="save-icon"></span><span>${s}</span></button>`).join('')}</div><div class="ps-footer"><span>✕ Enter</span><span>○ Back</span><span>△ Options</span></div></div>`;
 case 'tv': return `<div class="tv-screen"><div class="tv-content"><div>AWAKEN PUBLIC ACCESS</div><div class="tv-price">$20.15</div><div>2 EASY PAYMENTS OF SIGNAL</div><div class="tv-phone">1-800-AWAKE-UP</div><button class="xp-button" data-action="channel">NEXT CHANNEL</button></div></div>`;
 case 'downloads': return `<div class="file-list">${['wallpaper_pack.zip','boot_animation.mov','icon_sheet.ico','flyer_print.pdf','screensaver.scr','discord_invite.url'].map((n,i)=>`<div class="file-row"><span>⬇</span><span>${n}</span><span>${i===5?'link':'pending'}</span><span>${i+1}.${i}MB</span></div>`).join('')}</div><p><button class="xp-button" data-action="download">DOWNLOAD WALLPAPER</button></p>`;
 case 'trash': return `<div class="file-list">${['rejected_logo_03.gif','shirt_final_final_REAL.psd','cancelled_drop_names.txt','do_not_post.jpg','old_dvd_site.html','bad_idea.exe'].map(n=>`<div class="file-row"><span>✕</span><span>${n}</span><span>deleted</span><span>?</span></div>`).join('')}</div>`;
 default:return 'File missing.'}}
function renderAim(openBuddy='music'){const buddies=['music','collection','archive','josh','discord','unknown_user'];return `<div class="social-shell"><div class="social-header"><span>AOL System Msg</span><span>Warning Level: 0%</span></div><div style="display:grid;grid-template-columns:130px 1fr;min-height:330px"><div style="background:#eee;border-right:1px solid #999;padding:8px">${buddies.map(b=>`<button class="xp-button aim-buddy" data-buddy="${b}" style="width:100%;margin-bottom:5px;text-align:left">${b}</button>`).join('')}</div><div style="padding:8px;background:#fff"><div id="aimLog" style="border:1px inset #999;min-height:230px;padding:8px;font-family:var(--mono)"></div><div style="margin-top:8px"><input style="width:78%" value="" placeholder="type message"><button class="xp-button" data-action="aim-send">Send</button></div></div></div></div>`}
function wireWindow(win,id){win.addEventListener('mousedown',()=>{win.style.zIndex=++z;$$('.window').forEach(w=>w.classList.remove('active'));win.classList.add('active')});win.querySelector('[data-close]')?.addEventListener('click',()=>closeWin(id));win.querySelector('[data-min]')?.addEventListener('click',()=>{win.style.display='none';updateTasks()});win.querySelectorAll('[data-action]').forEach(btn=>btn.addEventListener('click',()=>handleAction(btn.dataset.action,id)));if(id==='aim'){const load=b=>{const log=win.querySelector('#aimLog');log.innerHTML=`<b>${b}</b> is typing...<br><br>`;setTimeout(()=>{log.innerHTML+=aimMsgs(b).map(m=>`<div><b>${b}:</b> ${m}</div>`).join('')},500)};win.querySelectorAll('.aim-buddy').forEach(b=>b.onclick=()=>load(b.dataset.buddy));load('music')} if(id==='memory')win.querySelectorAll('.save').forEach(s=>s.onclick=()=>toast('save file damaged: '+s.textContent.trim()))}
function aimMsgs(b){return {music:['signal detected','not public yet','keep the player open'],collection:['package incomplete','4 garments detected','installer unstable'],archive:['some folders need stronger signal','do not trust final_final.psd'],josh:['still building','ask again later'],discord:['room is open',DISCORD],unknown_user:['...','you found this fast','konami code opens the real folder']}[b]||['away']}
function handleAction(action,id){if(action==='play')playBeep(true); if(action==='glitch'){document.body.classList.add('glitch');setTimeout(()=>document.body.classList.remove('glitch'),600)} if(action==='spawn'||action==='ad')spawnAd(); if(action==='channel')spawnAd('TRANSMISSION INTERRUPTION'); if(action==='download')toast('download queued: wallpaper_pack.zip'); if(action==='aim-send')toast('message failed: server is awake but not listening')}
function closeWin(id){openWindows.get(id)?.remove();openWindows.delete(id);updateTasks()}
function updateTasks(){const t=$('#taskList');t.innerHTML='';openWindows.forEach((win,id)=>{const app=apps.find(a=>a.id===id);const b=document.createElement('button');b.textContent=app.label;b.onclick=()=>{win.style.display='flex';win.style.zIndex=++z};t.appendChild(b)})}
function makeDrag(win){const bar=win.querySelector('.titlebar');let sx,sy,ox,oy,drag=false;bar.addEventListener('pointerdown',e=>{if(innerWidth<720)return;drag=true;sx=e.clientX;sy=e.clientY;ox=parseInt(win.style.left)||0;oy=parseInt(win.style.top)||0;bar.setPointerCapture(e.pointerId)});bar.addEventListener('pointermove',e=>{if(!drag)return;win.style.left=Math.max(0,ox+e.clientX-sx)+'px';win.style.top=Math.max(0,oy+e.clientY-sy)+'px'});bar.addEventListener('pointerup',()=>drag=false)}
function spawnAd(title){const data=popupData.find(p=>p.t===title)||popupData[Math.floor(Math.random()*popupData.length)];const ad=document.createElement('div');ad.className='ad '+(data.kind==='virus'?'virus':'');ad.style.left=Math.max(8,Math.random()*(innerWidth-340))+'px';ad.style.top=Math.max(52,Math.random()*(innerHeight-280))+'px';ad.innerHTML=`<div class="ad-title"><span>${data.t}</span><button>×</button></div><div class="ad-body"><div class="${data.kind==='gif'||data.kind==='blue'?'ad-gif':''}">${data.kind==='gif'?'GIF GIFT IRL':data.kind==='blue'?'CALL TODAY':''}</div><p>${data.b}</p><button class="xp-button">${data.cta}</button></div>`;$('#popups').appendChild(ad);ad.querySelector('.ad-title button').onclick=()=>ad.remove();ad.querySelector('.ad-body button').onclick=()=>{playBeep(); if(data.t.includes('COLLECTION'))openApp('collection'); else if(data.t.includes('WALLPAPER'))openApp('downloads'); else if(data.t.includes('SECURITY')){openApp('archive','secret');toast('scan recovered one hidden file')} else spawnAd(); ad.remove()};setTimeout(()=>ad.isConnected&&ad.classList.add('glitch'),350)}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>t.classList.remove('show'),2300)}
function makeBeep(){const a=$('#beep');const ctxOK=typeof AudioContext!=='undefined'||typeof webkitAudioContext!=='undefined'; if(!ctxOK)return; // generated on demand instead
}
function playBeep(long=false){if(!sound)return;try{const C=window.AudioContext||window.webkitAudioContext;const ctx=new C();const o=ctx.createOscillator();const g=ctx.createGain();o.type='square';o.frequency.value=long?220:880;g.gain.value=.035;o.connect(g);g.connect(ctx.destination);o.start();setTimeout(()=>{o.stop();ctx.close()},long?450:70)}catch(e){}}
